<a href="https://colab.research.google.com/github/vbaezfortunato/Python_class/blob/master/XOR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# XOR

In [70]:
def not_(x1):
    parameters = [ -1 , 1]
    
    r = int(x1*parameters[0] + parameters[1]) 
    
    return r

In [71]:
not_(0)

1

In [72]:
not_(1)

0

In [73]:
def or_(x1, x2):
    parameters = [1, 1, 0]
    
    r = int(x1*parameters[0] + x2*parameters[1] + parameters[2] > 0)
    
    return r

In [74]:
 or_(0,0)

0

In [75]:
or_(0,1)

1

In [76]:
or_(1,1)

1

In [77]:
def and_(x1,x2):
    parameters = [1,1,-1]
    
    r = int(x1*parameters[0] + x2*parameters[1] + parameters[2] > 0)
    
    return r

In [78]:
and_(0,0)

0

In [79]:
and_(0,1)

0

In [80]:
and_(1,1)

1

In [81]:
def xor_(x1,x2):

    x1_temp = not_function(and_function(x1,x2))
    x2_temp = or_function(x1,x2)
    
    r = and_function(x1_temp, x2_temp)
    
    return r

# Segunda Parte

In [82]:

import numpy as np

In [95]:
m_ = np.array([[1,0,0],
              [0,1,0],
              [1,1,1]])

In [84]:

w = np.random.normal(0, 0.01, 6)

In [85]:

tensor = m_[:, 0:2]

In [86]:
tensor = np.insert(tensor, 0, np.ones(len(tensor)), axis=1).astype(np.float32)

verificando las variables 

In [87]:
m_

array([[1, 0, 0],
       [0, 1, 0],
       [1, 1, 0],
       [1, 1, 1]])

In [88]:
w

array([-0.00182302, -0.01033056,  0.00421657, -0.00319493,  0.01579389,
       -0.00896235])

In [89]:
tensor

array([[1., 1., 0.],
       [1., 0., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

# perceptrones entrenados

In [98]:
def train_(dataset, lr):
    train = dataset[:,0:2]
    train_label = dataset[:,2]
    w = np.random.normal(0, 0.1, 3)
    train = np.insert(train, 0, np.ones(len(train)), axis=1).astype(np.float32)
    
    
    result = np.dot(train,w) >= 0
    
    result = result.astype(int)
                      
    comparison_array = train_label == result
                 
    print(w)
    
    counter = 0
    while comparison_array.all() == False:
        
        for i in range(0,len(train_label)):
            
            if train_label[i] == 1 and np.dot(train[i],w) < 0:
                w = w + (lr * train[i])
                
            
            elif train_label[i] == 0 and np.dot(train[i],w) >= 0:
                w = w - (lr * train[i])
               
        result_temp = np.dot(train,w) >= 0
        result_temp = result_temp.astype(int)
        comparison_array = train_label == result_temp
        counter += 1
        print('iter:' + str(counter))
        print('Weight: ' + str(w))
        print('**************************************************************************')
    
    print('final:' + str(w))
    return w

In [101]:
train_(m_,0.01)

[ 0.02544886 -0.03599922 -0.18627854]
iter:1
Weight: [ 0.03544886 -0.02599922 -0.17627855]
**************************************************************************
iter:2
Weight: [ 0.03544886 -0.02599922 -0.16627855]
**************************************************************************
iter:3
Weight: [ 0.03544886 -0.02599922 -0.15627855]
**************************************************************************
iter:4
Weight: [ 0.03544886 -0.02599922 -0.14627855]
**************************************************************************
iter:5
Weight: [ 0.03544886 -0.02599922 -0.13627855]
**************************************************************************
iter:6
Weight: [ 0.03544886 -0.02599922 -0.12627855]
**************************************************************************
iter:7
Weight: [ 0.03544886 -0.02599922 -0.11627855]
**************************************************************************
iter:8
Weight: [ 0.03544886 -0.02599922 -0.10627855]
*************

array([-0.01455113,  0.00400078,  0.01372145])

In [102]:
train_(m_,0.001)

[-0.00770154 -0.00965599 -0.031692  ]
iter:1
Weight: [-0.00670154 -0.00865599 -0.030692  ]
**************************************************************************
iter:2
Weight: [-0.00570154 -0.00765599 -0.029692  ]
**************************************************************************
iter:3
Weight: [-0.00470154 -0.00665599 -0.028692  ]
**************************************************************************
iter:4
Weight: [-0.00370154 -0.00565599 -0.027692  ]
**************************************************************************
iter:5
Weight: [-0.00270154 -0.00465599 -0.026692  ]
**************************************************************************
iter:6
Weight: [-0.00170154 -0.00365599 -0.025692  ]
**************************************************************************
iter:7
Weight: [-0.00070154 -0.00265599 -0.024692  ]
**************************************************************************
iter:8
Weight: [ 0.00029846 -0.00165599 -0.023692  ]
*************

array([-0.00270154,  0.00134401,  0.002308  ])

In [103]:
train_(m_,0.0001)

[-0.02835621 -0.00215106  0.01073393]
iter:1
Weight: [-0.02825621 -0.00205106  0.01083393]
**************************************************************************
iter:2
Weight: [-0.02815621 -0.00195106  0.01093393]
**************************************************************************
iter:3
Weight: [-0.02805621 -0.00185106  0.01103393]
**************************************************************************
iter:4
Weight: [-0.02795621 -0.00175106  0.01113393]
**************************************************************************
iter:5
Weight: [-0.02785621 -0.00165106  0.01123393]
**************************************************************************
iter:6
Weight: [-0.02775621 -0.00155106  0.01133393]
**************************************************************************
iter:7
Weight: [-0.02765621 -0.00145106  0.01143393]
**************************************************************************
iter:8
Weight: [-0.02755621 -0.00135106  0.01153393]
*************

array([-0.02175621,  0.00444894,  0.01733393])

In [104]:
train_(m_,0.0001)

Streaming output truncated to the last 5000 lines.
iter:1611
Weight: [ 0.05785361 -0.05028412 -0.05768152]
**************************************************************************
iter:1612
Weight: [ 0.05775361 -0.05028412 -0.05768152]
**************************************************************************
iter:1613
Weight: [ 0.05775361 -0.05028412 -0.05758152]
**************************************************************************
iter:1614
Weight: [ 0.05765361 -0.05028412 -0.05758152]
**************************************************************************
iter:1615
Weight: [ 0.05765361 -0.05028412 -0.05748152]
**************************************************************************
iter:1616
Weight: [ 0.05755361 -0.05028412 -0.05748152]
**************************************************************************
iter:1617
Weight: [ 0.05755361 -0.05028412 -0.05738152]
**************************************************************************
iter:1618
Weight: [ 0.05745361 -

array([-0.00024639,  0.00011588,  0.00021848])